W4D5-Capybara/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except:[:new, :index]

end

W4D5-Capybara/music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :band_id, :title, :year, presence: true
  validates :live, inclusion: { in: [true, false]}

  belongs_to :band,
  foreign_key: :band_id,
  class_name: :Band

  has_many :tracks,
  foreign_key: :album_id,
  class_name: :Track,
  dependent: :destroy
end

W4D5-Capybara/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  foreign_key: :band_id,
  class_name: :Album,
  dependent: :destroy

end

W4D5-Capybara/music_app/app/models/track.rb
class Track < ApplicationRecord
  validates :album_id, :ord, :title, presence: true
  validates :bonus, inclusion: { in: [true, false]}

  belongs_to :album,
  foreign_key: :album_id,
  class_name: :Album
end

W4D5-Capybara/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness:true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
end

W4D5-Capybara/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_url(@album.band_id)
    else
      flash[:error] = @album.errors.full_messages
      redirect_to new_band_album_url
    end
  end

  def destroy
    @album = Album.find(params[:id])
    if @album
      @album.destroy
      redirect_to band_url(@album.band_id)
    else
      flash[:errors] = ["You tried to delete a non-existing album!"]
      redirect_to band_url(@album.band_id)
    end

  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update_attributes(album_params)
      redirect_to band_url(@album.band_id)
    else
      redirect_to edit_album_url
    end
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :title, :year, :live)
  end

end

W4D5-Capybara/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end
end

W4D5-Capybara/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash[:error] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def destroy
    @band = Band.find(params[:id])
    if @band
      @band.destroy
      redirect_to bands_url
    else
      flash[:errors] = ["You tried to delete a non-existing band!"]
      redirect_to bands_url
    end

  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])

    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      redirect_to edit_band_url
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

W4D5-Capybara/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      render json: @user.errors.full_messages
    end
  end

  def destroy
    logout!
  end

end

W4D5-Capybara/music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def show
    @track = Track.find(params[:id])
  end

  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to album_url(@track.album_id)
    else
      flash[:error] = @track.errors.full_messages
      redirect_to new_album_track_url
    end
  end

  def destroy
    @track = Track.find(params[:id])
    if @track
      @track.destroy
      redirect_to album_url(@track.album_id)
    else
      flash[:errors] = ["You tried to delete a non-existing track!"]
      redirect_to album_url(@track.album_id)
    end

  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])

    if @track.update_attributes(track_params)
      redirect_to album_url(@track.album_id)
    else
      redirect_to edit_track_url
    end
  end

  private
  def track_params
    params.require(:track).permit(:album_id, :title, :ord, :bonus)
  end

end

W4D5-Capybara/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @users = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      render json: @user.errors.full_messages
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D5-Capybara/music_app/app/views/albums/_albumform.html.erb
<%
if action == :new
  submit_text = "Create Album"
  action_url = albums_url
elsif action == :edit
  submit_text = "Update Album"
  action_url = album_url(album)
end
 %>

<% if flash[:error] %>
<ol>


  <% flash[:error].each do |error| %>
  <li>error: <%= error %></li>
  <% end %>
  </ol>
<% end %>

<form class="" action="<%= action_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if action == :edit %>
  <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="title"> Album Title:
  <input type="text" name="album[title]" value="<%= album.title%>">
  </label>
  <label for="year"> Album Year:
  <input type="text" name="album[year]" value="<%= album.year%>">
  </label>
  <label for="live"> Album Live:
    <select name="album[live]">
      <option value="true" <%="selected" if album.live == true %>>True</option>
      <option value="false"<%="selected" if album.live == false %>>False</option>
    </select>
  </label>

  <label for="band">
   <!-- <input type="text" name="album[band_id]" value="<%= params[:band_id] %>"> -->
  <select name="album[band_id]">
   <% Band.all.each do |band| %>
       <option value="<%=band.id%>" <%="selected" if band.id == params[:band_id] %>><%= band.name %></option>
    <% end %>
   </select>
</label>

  <input type="submit" value="<%=submit_text%>">
</form>

W4D5-Capybara/music_app/app/views/albums/edit.html.erb
<%= render "albumform", action: :edit, album: @album %>

W4D5-Capybara/music_app/app/views/albums/new.html.erb
<%= render "albumform", action: :new, album: @album %>

W4D5-Capybara/music_app/app/views/albums/show.html.erb
<table>
  <tr>
    <td> Band </td>
    <td> Title </td>
    <td> Year </td>
    <td> Live </td>
  </tr>
  <tr>
    <td><%= @album.band.name %></td>
    <td><%= @album.title%></td>
    <td><%= @album.year%></td>
    <td><%= @album.live%></td>
    <td><a href="<%=edit_album_url(@album)%>"> Edit Album</a> </td>
    <td>
      <form action="<%=album_url(@album)%>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="submit" value="Delete Album">
      </form>
    </td>
  </tr>
</table>

<br>
<br>

<a href="<%= new_album_track_url(@album.id) %>"> Create new track</a>

<table>
  <tr>
    <td>Title</td>
    <td>Track #</td>
    <td>Bonus</td>
  </tr>
<% @album.tracks.each do |track| %>
<tr>
  <td><%= track.title%></td>
  <td><%= track.ord%></td>
  <td><%= track.bonus%></td>
  <td><a href="<%=edit_track_url(track)%>"> Edit Track</a> </td>
  <td>
    <form action="<%=track_url(track)%>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
      <input type="submit" value="Delete Track">
    </form>
  </td>
</tr>
<% end %>
</table>

W4D5-Capybara/music_app/app/views/bands/_bandform.html.erb
<%
if action == :new
  submit_text = "Create Band"
  action_url = bands_url
elsif action == :edit
  submit_text = "Update Band"
  action_url = band_url(@band)
end
 %>

<% if flash[:error] %>
<ol>


  <% flash[:error].each do |error| %>
  <li>error: <%= error %></li>
  <% end %>
  </ol>
<% end %>

<form class="" action="<%= action_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if action == :edit %>
  <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="name">Band name:
  <input type="text" name="band[name]" value="<%= band.name%>">
  </label>

  <input type="submit" value="<%=submit_text%>">
</form>

W4D5-Capybara/music_app/app/views/bands/edit.html.erb
<!-- edit band -->
<%= render "bandform", band: @band, action: :edit %>

W4D5-Capybara/music_app/app/views/bands/index.html.erb
<!-- index band -->

<a href="<%=new_band_url%>"> Create Band</a>
<h1>All the Bands!!!</h1>
<table style = "width:100%">
  <% @bands.each do |band| %>
  <tr>
  <td><%=  band.name %></td>
  <td><a href="<%=band_url(band)%>">Info</a></td>
  <td><a href="<%=edit_band_url(band)%>"> Edit Band</a> </td>
  <td>
    <form action="<%=band_url(band)%>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
      <input type="submit" value="Delete Band">
    </form>
  </td>
  </tr>

  <% end %>
  </table>
</ol>

W4D5-Capybara/music_app/app/views/bands/new.html.erb
<!-- new band -->
<%= render "bandform", band: @band, action: :new %>

W4D5-Capybara/music_app/app/views/bands/show.html.erb
<!-- show band -->
<h1> <%= @band.name %> Albums </h1>
<table>
  <tr>
    <td> Title </td>
    <td> Year </td>
    <td> Live </td>
  </tr>
  <% @band.albums.each do |album| %>
  <tr>
    <td><%= album.title%></td>
    <td><%= album.year%></td>
    <td><%= album.live%></td>
    <td><a href="<%=edit_album_url(album)%>"> Edit Album</a> </td>
    <td>
      <form action="<%=album_url(album)%>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="submit" value="Delete Album">
      </form>
    </td>
  </tr>
  <% end %>
</table>


<a href="<%=new_band_album_url(params[:id])%>">Create Album</a><br>
<a href="<%= bands_url%>"> Back to All Bands</a>

W4D5-Capybara/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
  header {
    color: blue;
    font-size: 30px;

  }

  a {
    background-color: aqua;
    border-radius: 2px
    border: 1px solid blue;
  }

  nav {
    display: flex;
    justify-content: space-around;

  }

  table, th, td {
   border: 1px solid black;
}

  </style>

  <nav>
  <header> Music App </header>


  <% unless logged_in? %>
  <a href="<%=new_session_url%>">Log In</a>
  <a href="<%=new_user_url%>">Sign Up</a>
  <% else %>
  <form action="<%=session_url%>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="submit" value="Log Out">
  </form>
  <% end %>
    </nav>

  <body>
    <%= yield %>
  </body>
</html>

W4D5-Capybara/music_app/app/views/tracks/_trackform.html.erb
<%
if action == :new
  submit_text = "Create Track"
  action_url = tracks_url
elsif action == :edit
  submit_text = "Update Track"
  action_url = track_url(track)
end
 %>

<% if flash[:error] %>
<ol>


  <% flash[:error].each do |error| %>
  <li>error: <%= error %></li>
  <% end %>
  </ol>
<% end %>

<form class="" action="<%= action_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if action == :edit %>
  <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="title"> Track Title:
  <input type="text" name="track[title]" value="<%= track.title%>">
  </label>
  <label for="ord"> Track Number:
  <input type="text" name="track[ord]" value="<%= track.ord%>">
  </label>
  <label for="bonus"> Track Bonus:
    <select name="track[bonus]">
      <option value="true" <%="selected" if track.bonus == true %>>True</option>
      <option value="false"<%="selected" if track.bonus == false %>>False</option>
    </select>
  </label>

  <label for="track"> Album
   <!-- <input type="text" name="track[track_id]" value="<%= params[:track_id] %>"> -->
  <select name="track[album_id]">
   <% Album.all.each do |album| %>
       <option value="<%=album.id%>" <%="selected" if album.id == params[:album_id] %>><%= album.title %></option>
    <% end %>
   </select>
</label>

<textarea name="track[lyrics]" rows="8" cols="120"><%= track.lyrics %></textarea>
<br>
  <input type="submit" value="<%=submit_text%>">
</form>

W4D5-Capybara/music_app/app/views/tracks/edit.html.erb
<%= render "trackform", action: :edit, track: @track %>

W4D5-Capybara/music_app/app/views/tracks/new.html.erb
<%= render "trackform", action: :new, track: @track %>

W4D5-Capybara/music_app/app/views/tracks/show.html.erb
<ul>
  <li>Track #<%=@track.ord %></li>
  <li>Title: <%=@track.title %></li>
  <li>Bonus: <%=@track.bonus %></li>
  <li>Lyrics: <%=@track.lyrics %></li>
</ul>

W4D5-Capybara/music_app/app/views/users/new.html.erb
<!-- new user -->
<h3>Sign Up</h3>

<form action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label for="email"> Email:
  <input type="text" name="user[email]" value="">
</label> <br>
  <label for="email"> Password:
  <input type="text" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">

</form>

W4D5-Capybara/music_app/app/views/users/show.html.erb
<!-- show user -->
<h1>Hello, <%= @user.email %></h1>